# services:
#    acme_product.example:
#        class: Acme\Bundle\ProductBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

services:
  acme.form.type.product:
    class: 'Acme\Bundle\ProductBundle\Form\ProductType'
    tags:
      -  { name: form.type, alias: 'acme_product_type' }

  acme.form.type.serie:
    class: 'Acme\Bundle\ProductBundle\Form\SerieType'
    tags:
      -  { name: form.type, alias: 'acme_serie_type' }
