acme_cpanel_product_index:
    path:     /
    defaults: { _controller: "AcmeProductBundle:Product:index" }
    methods:  GET

acme_cpanel_product_show:
    path:     /{id}/show
    defaults: { _controller: "AcmeProductBundle:Product:show" }
    methods:  GET

acme_cpanel_product_new:
    path:     /new
    defaults: { _controller: "AcmeProductBundle:Product:new" }
    methods:  [GET, POST]

acme_cpanel_product_edit:
    path:     /{id}/edit
    defaults: { _controller: "AcmeProductBundle:Product:edit" }
    methods:  [GET, POST]

acme_cpanel_product_delete:
    path:     /{id}/delete
    defaults: { _controller: "AcmeProductBundle:Product:delete" }
    methods:  DELETE
